on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekout@v3
      - name: "docker login"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}
      - name: "docker build"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/image .
      - name: "docker push"
        run: docker push ${{secrets.DOCKER_USERNAME}}/image